server:
    port: 8085
    servlet:
        context-path: /L1


spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/DoAnKhanh"
        username: root
        password: root


    servlet:
        multipart:
            enabled: true           # Kích hoạt xử lý multipart
            max-file-size: 10MB     # Kích thước tối đa của file
            max-request-size: 10MB  # Kích thước tối đa của request

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

jwt:
    expiryTime: 3600000
    secretKey: b8ad08a3a547e35829b821b75370301dd8c4b06bdd7771f9b541a75914068718
    refreshKey: usGdYRIuPQoxmZEHoGMZ+P+csgy0kpJQQS6KDDNRSmU=
