server:
    port: 8085
    servlet:
        context-path: /L1
        session:
            timeout: 24h


spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/dbWebDoAn"
        username: root
        password: root
    main:
        allow-circular-references: true


    servlet:
        multipart:
            enabled: true           # Kích hoạt xử lý multipart
            max-file-size: 10MB     # Kích thước tối đa của file
            max-request-size: 10MB  # Kích thước tối đa của request

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false

jwt:
    expiryTime: 604800000
    secretKey: b8ad08a3a547e35829b821b75370301dd8c4b06bdd7771f9b541a75914068718
    refreshKey: usGdYRIuPQoxmZEHoGMZ+P+csgy0kpJQQS6KDDNRSmU=
